// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct BolaoProgram;
impl sails_rs::client::Program for BolaoProgram {}
pub trait Bolao {
    type Env: sails_rs::client::GearEnv;
    fn service(&self) -> sails_rs::client::Service<service::ServiceImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> Bolao for sails_rs::client::Actor<BolaoProgram, E> {
    type Env = E;
    fn service(&self) -> sails_rs::client::Service<service::ServiceImpl, Self::Env> {
        self.service(stringify!(Service))
    }
}
pub trait BolaoCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        admin: ActorId,
        treasury: ActorId,
    ) -> sails_rs::client::PendingCtor<BolaoProgram, io::New, Self::Env>;
    /// Deploy in importer mode: migration_sealed=false.
    /// All user-facing writes are blocked until seal_migration() is called.
    fn new_as_importer(
        self,
        admin: ActorId,
        treasury: ActorId,
    ) -> sails_rs::client::PendingCtor<BolaoProgram, io::NewAsImporter, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> BolaoCtors for sails_rs::client::Deployment<BolaoProgram, E> {
    type Env = E;
    fn new(
        self,
        admin: ActorId,
        treasury: ActorId,
    ) -> sails_rs::client::PendingCtor<BolaoProgram, io::New, Self::Env> {
        self.pending_ctor((admin, treasury))
    }
    fn new_as_importer(
        self,
        admin: ActorId,
        treasury: ActorId,
    ) -> sails_rs::client::PendingCtor<BolaoProgram, io::NewAsImporter, Self::Env> {
        self.pending_ctor((admin, treasury))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (admin: ActorId, treasury: ActorId) -> ());
    sails_rs::io_struct_impl!(NewAsImporter (admin: ActorId, treasury: ActorId) -> ());
}

pub mod service {
    use super::*;
    pub trait Service {
        type Env: sails_rs::client::GearEnv;
        /// Adds a new admin to the admins list. Any existing admin can call this.
        fn add_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddAdmin, Self::Env>;
        /// Adds an operator. Only admins can call this.
        /// Operators can call register_phase and register_match.
        fn add_operator(
            &mut self,
            new_operator: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddOperator, Self::Env>;
        /// T21 — Admin push refund: sends a user's pending refund on their behalf.
        /// Does NOT call check_writes_allowed() — valid even during migration lock
        /// so admins can drain refunds before drain_vara_to (REQ-11.5).
        /// Follows CEI: clears bookkeeping before send; restores on failure.
        fn admin_push_refund(
            &mut self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::AdminPushRefund, Self::Env>;
        /// Marks a match as Cancelled and accumulates per-bettor refunds in
        /// pending_refunds. Use when a match cannot or will not produce a real
        /// result (suspension, abandonment, FIFA voiding, registration error).
        /// Cash bettors then call claim_refund() to pull their stake out. Freebet
        /// principal is returned to FreebetLedger immediately during cancellation
        /// because no finalized match payout exists.
        ///
        /// Cash refund amount per bettor = stake_in_match_pool (the 85% post-fee
        /// share). Freebet refund amount = stake_in_match_pool, because freebet
        /// entries do not pay protocol/final-prize fees. Once a match is finalized,
        /// winning freebet claims return the principal to FreebetLedger and send
        /// only net winnings to the user's wallet.
        ///
        /// Cancelling a match is terminal — no transition out of Cancelled.
        /// Cannot cancel a match already Finalized (claims may have happened).
        fn cancel_match(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelMatch, Self::Env>;
        fn cancel_proposed_result(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelProposedResult, Self::Env>;
        fn claim_final_prize(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::ClaimFinalPrize, Self::Env>;
        fn claim_match_reward(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClaimMatchReward, Self::Env>;
        fn claim_refund(&mut self) -> sails_rs::client::PendingCall<io::ClaimRefund, Self::Env>;
        /// T17 — Drains the entire program balance to `dest`.
        /// Requires migration_locked == true and admin caller.
        fn drain_vara_to(
            &mut self,
            dest: ActorId,
        ) -> sails_rs::client::PendingCall<io::DrainVaraTo, Self::Env>;
        fn finalize_final_prize_pool(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::FinalizeFinalPrizePool, Self::Env>;
        fn finalize_podium(
            &mut self,
            champion: String,
            runner_up: String,
            third_place: String,
        ) -> sails_rs::client::PendingCall<io::FinalizePodium, Self::Env>;
        fn finalize_result(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeResult, Self::Env>;
        fn force_withdraw_vara(
            &mut self,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ForceWithdrawVara, Self::Env>;
        /// T19 — Imports scalar metadata.
        /// Requires migration_sealed == false and admin caller.
        /// Does NOT emit an event (REQ-8.5).
        fn import_metadata(
            &mut self,
            meta: MigrationMetadata,
        ) -> sails_rs::client::PendingCall<io::ImportMetadata, Self::Env>;
        /// T18 — Imports one page of state into this contract.
        /// Requires migration_sealed == false (importer mode) and admin caller.
        /// All inserts are idempotent (existing entries at the same key are overwritten).
        fn import_state_page(
            &mut self,
            page: MigrationPage,
        ) -> sails_rs::client::PendingCall<io::ImportStatePage, Self::Env>;
        /// T13 — Locks the contract for migration (SOURCE role).
        /// Snapshots all collection keys into sorted Vecs; blocks all user writes.
        /// Idempotent: calling again when already locked is a no-op.
        fn lock_for_migration(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::LockForMigration, Self::Env>;
        fn place_bet(
            &mut self,
            match_id: u64,
            predicted_score: Score,
            predicted_penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::PlaceBet, Self::Env>;
        fn place_bet_from_freebet_ledger(
            &mut self,
            user: ActorId,
            match_id: u64,
            predicted_score: Score,
            predicted_penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::PlaceBetFromFreebetLedger, Self::Env>;
        fn propose_from_oracle(
            &mut self,
            match_id: u64,
            oracle_program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::ProposeFromOracle, Self::Env>;
        fn propose_result(
            &mut self,
            match_id: u64,
            final_score: Score,
            penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::ProposeResult, Self::Env>;
        /// Queries the Oracle-Program for the current VARA/USD price and caches it.
        /// Must be called by an admin or operator. oracle_program_id must match an
        /// authorized oracle or the stored price_oracle_program_id.
        fn refresh_vara_price(
            &mut self,
            oracle_program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::RefreshVaraPrice, Self::Env>;
        fn register_match(
            &mut self,
            phase: String,
            home: String,
            away: String,
            kick_off: u64,
        ) -> sails_rs::client::PendingCall<io::RegisterMatch, Self::Env>;
        fn register_phase(
            &mut self,
            phase_name: String,
            start_time: u64,
            end_time: u64,
            points_weight: u32,
        ) -> sails_rs::client::PendingCall<io::RegisterPhase, Self::Env>;
        /// Removes an admin from the admins list. Any existing admin can call this.
        /// Panics if trying to remove the last admin.
        fn remove_admin(
            &mut self,
            admin_to_remove: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveAdmin, Self::Env>;
        /// Removes an operator. Only admins can call this.
        fn remove_operator(
            &mut self,
            operator_to_remove: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveOperator, Self::Env>;
        /// T20 — Seals the contract after import is complete.
        /// Flips migration_sealed to true, re-enables all writes, clears index Vecs.
        fn seal_migration(&mut self)
        -> sails_rs::client::PendingCall<io::SealMigration, Self::Env>;
        fn set_freebet_ledger(
            &mut self,
            ledger_program_id: Option<ActorId>,
        ) -> sails_rs::client::PendingCall<io::SetFreebetLedger, Self::Env>;
        fn set_oracle_authorized(
            &mut self,
            oracle: ActorId,
            authorized: bool,
        ) -> sails_rs::client::PendingCall<io::SetOracleAuthorized, Self::Env>;
        fn set_price_oracle(
            &mut self,
            oracle_program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetPriceOracle, Self::Env>;
        fn set_price_staleness_limit(
            &mut self,
            staleness_limit_ms: u64,
        ) -> sails_rs::client::PendingCall<io::SetPriceStalenessLimit, Self::Env>;
        /// Updates the treasury address. Only admins can call this.
        /// The treasury receives protocol fees and rounding dust.
        fn set_treasury(
            &mut self,
            new_treasury: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetTreasury, Self::Env>;
        fn submit_podium_pick(
            &mut self,
            champion: String,
            runner_up: String,
            third_place: String,
        ) -> sails_rs::client::PendingCall<io::SubmitPodiumPick, Self::Env>;
        fn sweep_match_dust_to_final_prize(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::SweepMatchDustToFinalPrize, Self::Env>;
        fn withdraw_final_prize_rounding_dust(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::WithdrawFinalPrizeRoundingDust, Self::Env>;
        fn withdraw_protocol_fees(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::WithdrawProtocolFees, Self::Env>;
        fn withdraw_surplus_vara(
            &mut self,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawSurplusVara, Self::Env>;
        fn contract_version_4(
            &self,
        ) -> sails_rs::client::PendingCall<io::ContractVersion4, Self::Env>;
        /// T16 — Returns all scalar metadata from state.
        /// Requires migration_locked == true. Does NOT emit an event (query-style).
        fn export_metadata(&self) -> sails_rs::client::PendingCall<io::ExportMetadata, Self::Env>;
        /// T15 — Returns a deterministic page of state.
        /// Requires migration_locked == true. page_size is silently capped to MAX_MIGRATION_PAGE_SIZE.
        fn export_state_page(
            &self,
            page: u32,
            page_size: u32,
        ) -> sails_rs::client::PendingCall<io::ExportStatePage, Self::Env>;
        fn query_bets_by_user(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryBetsByUser, Self::Env>;
        fn query_final_prize_claim_status(
            &self,
            wallet: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryFinalPrizeClaimStatus, Self::Env>;
        /// Returns the total VARA (planck) the contract holds on behalf of users.
        /// Useful for off-chain tooling to compute the correct amount before drain_vara_to.
        fn query_locked_vara(
            &self,
        ) -> sails_rs::client::PendingCall<io::QueryLockedVara, Self::Env>;
        fn query_match(
            &self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::QueryMatch, Self::Env>;
        fn query_matches_by_phase(
            &self,
            phase: String,
        ) -> sails_rs::client::PendingCall<io::QueryMatchesByPhase, Self::Env>;
        fn query_pending_refund(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryPendingRefund, Self::Env>;
        fn query_state(&self) -> sails_rs::client::PendingCall<io::QueryState, Self::Env>;
        fn query_user_points(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryUserPoints, Self::Env>;
        fn query_wallet_claim_status(
            &self,
            wallet: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryWalletClaimStatus, Self::Env>;
    }
    pub struct ServiceImpl;
    impl<E: sails_rs::client::GearEnv> Service for sails_rs::client::Service<ServiceImpl, E> {
        type Env = E;
        fn add_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddAdmin, Self::Env> {
            self.pending_call((new_admin,))
        }
        fn add_operator(
            &mut self,
            new_operator: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddOperator, Self::Env> {
            self.pending_call((new_operator,))
        }
        fn admin_push_refund(
            &mut self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::AdminPushRefund, Self::Env> {
            self.pending_call((user,))
        }
        fn cancel_match(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelMatch, Self::Env> {
            self.pending_call((match_id,))
        }
        fn cancel_proposed_result(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelProposedResult, Self::Env> {
            self.pending_call((match_id,))
        }
        fn claim_final_prize(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::ClaimFinalPrize, Self::Env> {
            self.pending_call(())
        }
        fn claim_match_reward(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClaimMatchReward, Self::Env> {
            self.pending_call((match_id,))
        }
        fn claim_refund(&mut self) -> sails_rs::client::PendingCall<io::ClaimRefund, Self::Env> {
            self.pending_call(())
        }
        fn drain_vara_to(
            &mut self,
            dest: ActorId,
        ) -> sails_rs::client::PendingCall<io::DrainVaraTo, Self::Env> {
            self.pending_call((dest,))
        }
        fn finalize_final_prize_pool(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::FinalizeFinalPrizePool, Self::Env> {
            self.pending_call(())
        }
        fn finalize_podium(
            &mut self,
            champion: String,
            runner_up: String,
            third_place: String,
        ) -> sails_rs::client::PendingCall<io::FinalizePodium, Self::Env> {
            self.pending_call((champion, runner_up, third_place))
        }
        fn finalize_result(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeResult, Self::Env> {
            self.pending_call((match_id,))
        }
        fn force_withdraw_vara(
            &mut self,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ForceWithdrawVara, Self::Env> {
            self.pending_call((to, amount))
        }
        fn import_metadata(
            &mut self,
            meta: MigrationMetadata,
        ) -> sails_rs::client::PendingCall<io::ImportMetadata, Self::Env> {
            self.pending_call((meta,))
        }
        fn import_state_page(
            &mut self,
            page: MigrationPage,
        ) -> sails_rs::client::PendingCall<io::ImportStatePage, Self::Env> {
            self.pending_call((page,))
        }
        fn lock_for_migration(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::LockForMigration, Self::Env> {
            self.pending_call(())
        }
        fn place_bet(
            &mut self,
            match_id: u64,
            predicted_score: Score,
            predicted_penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::PlaceBet, Self::Env> {
            self.pending_call((match_id, predicted_score, predicted_penalty_winner))
        }
        fn place_bet_from_freebet_ledger(
            &mut self,
            user: ActorId,
            match_id: u64,
            predicted_score: Score,
            predicted_penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::PlaceBetFromFreebetLedger, Self::Env> {
            self.pending_call((user, match_id, predicted_score, predicted_penalty_winner))
        }
        fn propose_from_oracle(
            &mut self,
            match_id: u64,
            oracle_program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::ProposeFromOracle, Self::Env> {
            self.pending_call((match_id, oracle_program_id))
        }
        fn propose_result(
            &mut self,
            match_id: u64,
            final_score: Score,
            penalty_winner: Option<PenaltyWinner>,
        ) -> sails_rs::client::PendingCall<io::ProposeResult, Self::Env> {
            self.pending_call((match_id, final_score, penalty_winner))
        }
        fn refresh_vara_price(
            &mut self,
            oracle_program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::RefreshVaraPrice, Self::Env> {
            self.pending_call((oracle_program_id,))
        }
        fn register_match(
            &mut self,
            phase: String,
            home: String,
            away: String,
            kick_off: u64,
        ) -> sails_rs::client::PendingCall<io::RegisterMatch, Self::Env> {
            self.pending_call((phase, home, away, kick_off))
        }
        fn register_phase(
            &mut self,
            phase_name: String,
            start_time: u64,
            end_time: u64,
            points_weight: u32,
        ) -> sails_rs::client::PendingCall<io::RegisterPhase, Self::Env> {
            self.pending_call((phase_name, start_time, end_time, points_weight))
        }
        fn remove_admin(
            &mut self,
            admin_to_remove: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveAdmin, Self::Env> {
            self.pending_call((admin_to_remove,))
        }
        fn remove_operator(
            &mut self,
            operator_to_remove: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveOperator, Self::Env> {
            self.pending_call((operator_to_remove,))
        }
        fn seal_migration(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::SealMigration, Self::Env> {
            self.pending_call(())
        }
        fn set_freebet_ledger(
            &mut self,
            ledger_program_id: Option<ActorId>,
        ) -> sails_rs::client::PendingCall<io::SetFreebetLedger, Self::Env> {
            self.pending_call((ledger_program_id,))
        }
        fn set_oracle_authorized(
            &mut self,
            oracle: ActorId,
            authorized: bool,
        ) -> sails_rs::client::PendingCall<io::SetOracleAuthorized, Self::Env> {
            self.pending_call((oracle, authorized))
        }
        fn set_price_oracle(
            &mut self,
            oracle_program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetPriceOracle, Self::Env> {
            self.pending_call((oracle_program_id,))
        }
        fn set_price_staleness_limit(
            &mut self,
            staleness_limit_ms: u64,
        ) -> sails_rs::client::PendingCall<io::SetPriceStalenessLimit, Self::Env> {
            self.pending_call((staleness_limit_ms,))
        }
        fn set_treasury(
            &mut self,
            new_treasury: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetTreasury, Self::Env> {
            self.pending_call((new_treasury,))
        }
        fn submit_podium_pick(
            &mut self,
            champion: String,
            runner_up: String,
            third_place: String,
        ) -> sails_rs::client::PendingCall<io::SubmitPodiumPick, Self::Env> {
            self.pending_call((champion, runner_up, third_place))
        }
        fn sweep_match_dust_to_final_prize(
            &mut self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::SweepMatchDustToFinalPrize, Self::Env> {
            self.pending_call((match_id,))
        }
        fn withdraw_final_prize_rounding_dust(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::WithdrawFinalPrizeRoundingDust, Self::Env> {
            self.pending_call(())
        }
        fn withdraw_protocol_fees(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::WithdrawProtocolFees, Self::Env> {
            self.pending_call(())
        }
        fn withdraw_surplus_vara(
            &mut self,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawSurplusVara, Self::Env> {
            self.pending_call((to, amount))
        }
        fn contract_version_4(
            &self,
        ) -> sails_rs::client::PendingCall<io::ContractVersion4, Self::Env> {
            self.pending_call(())
        }
        fn export_metadata(&self) -> sails_rs::client::PendingCall<io::ExportMetadata, Self::Env> {
            self.pending_call(())
        }
        fn export_state_page(
            &self,
            page: u32,
            page_size: u32,
        ) -> sails_rs::client::PendingCall<io::ExportStatePage, Self::Env> {
            self.pending_call((page, page_size))
        }
        fn query_bets_by_user(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryBetsByUser, Self::Env> {
            self.pending_call((user,))
        }
        fn query_final_prize_claim_status(
            &self,
            wallet: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryFinalPrizeClaimStatus, Self::Env> {
            self.pending_call((wallet,))
        }
        fn query_locked_vara(
            &self,
        ) -> sails_rs::client::PendingCall<io::QueryLockedVara, Self::Env> {
            self.pending_call(())
        }
        fn query_match(
            &self,
            match_id: u64,
        ) -> sails_rs::client::PendingCall<io::QueryMatch, Self::Env> {
            self.pending_call((match_id,))
        }
        fn query_matches_by_phase(
            &self,
            phase: String,
        ) -> sails_rs::client::PendingCall<io::QueryMatchesByPhase, Self::Env> {
            self.pending_call((phase,))
        }
        fn query_pending_refund(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryPendingRefund, Self::Env> {
            self.pending_call((user,))
        }
        fn query_state(&self) -> sails_rs::client::PendingCall<io::QueryState, Self::Env> {
            self.pending_call(())
        }
        fn query_user_points(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryUserPoints, Self::Env> {
            self.pending_call((user,))
        }
        fn query_wallet_claim_status(
            &self,
            wallet: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryWalletClaimStatus, Self::Env> {
            self.pending_call((wallet,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddAdmin (new_admin: ActorId) -> ());
        sails_rs::io_struct_impl!(AddOperator (new_operator: ActorId) -> ());
        sails_rs::io_struct_impl!(AdminPushRefund (user: ActorId) -> ());
        sails_rs::io_struct_impl!(CancelMatch (match_id: u64) -> ());
        sails_rs::io_struct_impl!(CancelProposedResult (match_id: u64) -> ());
        sails_rs::io_struct_impl!(ClaimFinalPrize () -> ());
        sails_rs::io_struct_impl!(ClaimMatchReward (match_id: u64) -> ());
        sails_rs::io_struct_impl!(ClaimRefund () -> ());
        sails_rs::io_struct_impl!(DrainVaraTo (dest: ActorId) -> ());
        sails_rs::io_struct_impl!(FinalizeFinalPrizePool () -> ());
        sails_rs::io_struct_impl!(FinalizePodium (champion: String, runner_up: String, third_place: String) -> ());
        sails_rs::io_struct_impl!(FinalizeResult (match_id: u64) -> ());
        sails_rs::io_struct_impl!(ForceWithdrawVara (to: ActorId, amount: u128) -> ());
        sails_rs::io_struct_impl!(ImportMetadata (meta: super::MigrationMetadata) -> ());
        sails_rs::io_struct_impl!(ImportStatePage (page: super::MigrationPage) -> ());
        sails_rs::io_struct_impl!(LockForMigration () -> ());
        sails_rs::io_struct_impl!(PlaceBet (match_id: u64, predicted_score: super::Score, predicted_penalty_winner: Option<super::PenaltyWinner>) -> ());
        sails_rs::io_struct_impl!(PlaceBetFromFreebetLedger (user: ActorId, match_id: u64, predicted_score: super::Score, predicted_penalty_winner: Option<super::PenaltyWinner>) -> u128);
        sails_rs::io_struct_impl!(ProposeFromOracle (match_id: u64, oracle_program_id: ActorId) -> ());
        sails_rs::io_struct_impl!(ProposeResult (match_id: u64, final_score: super::Score, penalty_winner: Option<super::PenaltyWinner>) -> ());
        sails_rs::io_struct_impl!(RefreshVaraPrice (oracle_program_id: ActorId) -> ());
        sails_rs::io_struct_impl!(RegisterMatch (phase: String, home: String, away: String, kick_off: u64) -> ());
        sails_rs::io_struct_impl!(RegisterPhase (phase_name: String, start_time: u64, end_time: u64, points_weight: u32) -> ());
        sails_rs::io_struct_impl!(RemoveAdmin (admin_to_remove: ActorId) -> ());
        sails_rs::io_struct_impl!(RemoveOperator (operator_to_remove: ActorId) -> ());
        sails_rs::io_struct_impl!(SealMigration () -> ());
        sails_rs::io_struct_impl!(SetFreebetLedger (ledger_program_id: Option<ActorId>) -> ());
        sails_rs::io_struct_impl!(SetOracleAuthorized (oracle: ActorId, authorized: bool) -> ());
        sails_rs::io_struct_impl!(SetPriceOracle (oracle_program_id: ActorId) -> ());
        sails_rs::io_struct_impl!(SetPriceStalenessLimit (staleness_limit_ms: u64) -> ());
        sails_rs::io_struct_impl!(SetTreasury (new_treasury: ActorId) -> ());
        sails_rs::io_struct_impl!(SubmitPodiumPick (champion: String, runner_up: String, third_place: String) -> ());
        sails_rs::io_struct_impl!(SweepMatchDustToFinalPrize (match_id: u64) -> ());
        sails_rs::io_struct_impl!(WithdrawFinalPrizeRoundingDust () -> ());
        sails_rs::io_struct_impl!(WithdrawProtocolFees () -> ());
        sails_rs::io_struct_impl!(WithdrawSurplusVara (to: ActorId, amount: u128) -> ());
        sails_rs::io_struct_impl!(ContractVersion4 () -> u32);
        sails_rs::io_struct_impl!(ExportMetadata () -> super::MigrationMetadata);
        sails_rs::io_struct_impl!(ExportStatePage (page: u32, page_size: u32) -> super::MigrationPage);
        sails_rs::io_struct_impl!(QueryBetsByUser (user: ActorId) -> Vec<super::UserBetView>);
        sails_rs::io_struct_impl!(QueryFinalPrizeClaimStatus (wallet: ActorId) -> super::FinalPrizeClaimStatus);
        sails_rs::io_struct_impl!(QueryLockedVara () -> u128);
        sails_rs::io_struct_impl!(QueryMatch (match_id: u64) -> Option<super::Match>);
        sails_rs::io_struct_impl!(QueryMatchesByPhase (phase: String) -> Vec<super::Match>);
        sails_rs::io_struct_impl!(QueryPendingRefund (user: ActorId) -> u128);
        sails_rs::io_struct_impl!(QueryState () -> super::IoSmartCupState);
        sails_rs::io_struct_impl!(QueryUserPoints (user: ActorId) -> u32);
        sails_rs::io_struct_impl!(QueryWalletClaimStatus (wallet: ActorId) -> super::WalletClaimStatus);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum ServiceEvents {
            PhaseRegistered(String),
            MatchRegistered((u64, String, String, String, u64)),
            OracleAuthorized((ActorId, bool)),
            BetAccepted((ActorId, u64, Score, Option<PenaltyWinner>, u128)),
            ResultProposed((u64, Score, Option<PenaltyWinner>, ActorId, u64)),
            ResultFinalized((u64, Score, Option<PenaltyWinner>)),
            SettlementPrepared((u64, u128)),
            PointsAwarded((ActorId, u64, u32)),
            MatchRewardClaimed((u64, ActorId, u128)),
            MatchDustSwept((u64, u128)),
            PodiumPickSubmitted((ActorId, String, String, String)),
            PodiumFinalized((String, String, String)),
            PodiumBonusAwarded((ActorId, u32)),
            FinalPrizeSent((u128, ActorId)),
            ProtocolFeesWithdrawn((u128, ActorId)),
            AdminAdded(ActorId),
            AdminRemoved(ActorId),
            OperatorAdded(ActorId),
            OperatorRemoved(ActorId),
            TreasuryChanged((ActorId, ActorId)),
            FinalPrizePoolFinalized((u128, u128)),
            FinalPrizeClaimed((ActorId, u128)),
            FinalPrizeRoundingDustWithdrawn((u128, ActorId)),
            SurplusVaraWithdrawn((u128, ActorId)),
            /// Admin emergency withdrawal that may bypass locked pools/liabilities: (amount, to).
            ForceVaraWithdrawn((u128, ActorId)),
            ResultProposalCancelled((u64, ActorId)),
            MatchCancelled((u64, u128)),
            RefundClaimed((ActorId, u128)),
            FreebetLedgerSet(Option<ActorId>),
            FreebetBetAccepted((ActorId, u64, Score, Option<PenaltyWinner>, u128)),
            FreebetPrincipalReturned((ActorId, u64, u128)),
            /// VARA/USD price refreshed from Oracle-Program: (price_usd_micro).
            VaraPriceRefreshed(u64),
            MigrationLocked,
            /// Emitted by export_state_page(): (page, entries_in_page).
            MigrationPageExported((u32, u32)),
            MigrationMetadataExported,
            /// Emitted by drain_vara_to(): (dest, amount).
            MigrationVaraDrained((ActorId, u128)),
            /// Emitted by import_state_page(): (page, entries_imported).
            MigrationPageImported((u32, u32)),
            MigrationMetadataImported,
            MigrationSealed,
            /// Emitted by admin_push_refund(): (user, amount).
            RefundPushed((ActorId, u128)),
        }
        impl sails_rs::client::Event for ServiceEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "PhaseRegistered",
                "MatchRegistered",
                "OracleAuthorized",
                "BetAccepted",
                "ResultProposed",
                "ResultFinalized",
                "SettlementPrepared",
                "PointsAwarded",
                "MatchRewardClaimed",
                "MatchDustSwept",
                "PodiumPickSubmitted",
                "PodiumFinalized",
                "PodiumBonusAwarded",
                "FinalPrizeSent",
                "ProtocolFeesWithdrawn",
                "AdminAdded",
                "AdminRemoved",
                "OperatorAdded",
                "OperatorRemoved",
                "TreasuryChanged",
                "FinalPrizePoolFinalized",
                "FinalPrizeClaimed",
                "FinalPrizeRoundingDustWithdrawn",
                "SurplusVaraWithdrawn",
                "ForceVaraWithdrawn",
                "ResultProposalCancelled",
                "MatchCancelled",
                "RefundClaimed",
                "FreebetLedgerSet",
                "FreebetBetAccepted",
                "FreebetPrincipalReturned",
                "VaraPriceRefreshed",
                "MigrationLocked",
                "MigrationPageExported",
                "MigrationMetadataExported",
                "MigrationVaraDrained",
                "MigrationPageImported",
                "MigrationMetadataImported",
                "MigrationSealed",
                "RefundPushed",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for ServiceImpl {
            type Event = ServiceEvents;
        }
    }
}
/// Scalar metadata exported from the source contract.
/// Used by `import_metadata` to restore non-collection state.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MigrationMetadata {
    pub admins: Vec<ActorId>,
    pub operators: Vec<ActorId>,
    pub treasury: ActorId,
    pub authorized_oracles: Vec<(ActorId, bool)>,
    pub next_match_id: u64,
    pub protocol_fee_accumulated: u128,
    pub final_prize_accumulated: u128,
    pub r32_lock_time: Option<u64>,
    pub podium_result: Option<PodiumResult>,
    pub podium_finalized: bool,
    pub final_prize_finalized: bool,
    pub final_prize_claimable_total: u128,
    pub final_prize_rounding_dust: u128,
    pub vara_price_usd_micro: u64,
    pub price_cached_at: u64,
    pub price_staleness_limit_ms: u64,
    pub price_oracle_program_id: Option<ActorId>,
    pub freebet_ledger_program_id: Option<ActorId>,
    /// Informational total of all pending_refunds; NOT persisted on import.
    pub pending_refunds_scalar: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PodiumResult {
    pub champion: String,
    pub runner_up: String,
    pub third_place: String,
}
/// One page of state data returned by `export_state_page`.
/// `matches` and `phases` are only populated on page 0 (they are small bounded sets).
/// `bets` and `user_payloads` are paginated by `page_size` per collection.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MigrationPage {
    pub page: u32,
    pub total_pages: u32,
    pub is_last_page: bool,
    pub matches: Vec<Match>,
    pub phases: Vec<PhaseConfig>,
    pub bets: Vec<Bet>,
    pub user_payloads: Vec<MigrationUserPayload>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Match {
    pub match_id: u64,
    pub phase: String,
    pub home: String,
    pub away: String,
    pub kick_off: u64,
    pub result: ResultStatus,
    pub match_prize_pool: u128,
    pub has_bets: bool,
    pub participants: Vec<ActorId>,
    pub total_winner_stake: u128,
    pub total_claimed: u128,
    pub settlement_prepared: bool,
    pub dust_swept: bool,
    pub finalized_at: Option<u64>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ResultStatus {
    Unresolved,
    Proposed {
        score: Score,
        penalty_winner: Option<PenaltyWinner>,
        oracle: ActorId,
        proposed_at: u64,
    },
    Finalized {
        score: Score,
        penalty_winner: Option<PenaltyWinner>,
    },
    Cancelled,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Score {
    pub home: u8,
    pub away: u8,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum PenaltyWinner {
    Home,
    Away,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PhaseConfig {
    pub name: String,
    pub start_time: u64,
    pub end_time: u64,
    pub points_weight: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Bet {
    pub user: ActorId,
    pub match_id: u64,
    pub score: Score,
    pub penalty_winner: Option<PenaltyWinner>,
    pub stake_in_match_pool: u128,
    pub freebet_principal: u128,
    pub claimed: bool,
}
/// Per-user payload bundling all user-keyed map entries for migration.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MigrationUserPayload {
    pub user: ActorId,
    pub user_bets: Vec<UserBetRecord>,
    pub user_points: u32,
    pub pending_refund: u128,
    pub podium_pick: Option<PodiumPick>,
    pub final_prize_allocation: u128,
    pub final_prize_claimed: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct UserBetRecord {
    pub match_id: u64,
    pub score: Score,
    pub penalty_winner: Option<PenaltyWinner>,
    pub stake_in_match_pool: u128,
    pub freebet_principal: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PodiumPick {
    pub champion: String,
    pub runner_up: String,
    pub third_place: String,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct UserBetView {
    pub match_id: u64,
    pub score: Score,
    pub penalty_winner: Option<PenaltyWinner>,
    pub stake_in_match_pool: u128,
    pub freebet_principal: u128,
    pub claimed: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct FinalPrizeClaimStatus {
    pub wallet: ActorId,
    pub final_prize_finalized: bool,
    pub eligible: bool,
    pub amount_claimable: u128,
    pub already_claimed: bool,
    pub points: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IoSmartCupState {
    pub admins: Vec<ActorId>,
    pub operators: Vec<ActorId>,
    pub treasury: ActorId,
    pub protocol_fee_accumulated: u128,
    pub final_prize_accumulated: u128,
    pub matches: Vec<Match>,
    pub phases: Vec<PhaseConfig>,
    pub user_points: Vec<(ActorId, u32)>,
    pub podium_finalized: bool,
    pub podium_result: Option<PodiumResult>,
    pub r32_lock_time: Option<u64>,
    pub final_prize_finalized: bool,
    pub final_prize_claimable_total: u128,
    pub final_prize_rounding_dust: u128,
    pub vara_price_usd_micro: u64,
    pub price_cached_at: u64,
    pub price_staleness_limit_ms: u64,
    pub freebet_ledger_program_id: Option<ActorId>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct WalletClaimStatus {
    pub wallet: ActorId,
    pub amount_claimable: u128,
    pub already_claimed: bool,
}
