// Code generated by sails-client-gen. DO NOT EDIT.
// Run `cargo build` inside DAO-SmartCupLeague-Program to regenerate from the current IDL.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct DaoProgram;
impl sails_rs::client::Program for DaoProgram {}
pub trait Dao {
    type Env: sails_rs::client::GearEnv;
    fn service(&self) -> sails_rs::client::Service<service::ServiceImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> Dao for sails_rs::client::Actor<DaoProgram, E> {
    type Env = E;
    fn service(&self) -> sails_rs::client::Service<service::ServiceImpl, Self::Env> {
        self.service(stringify!(Service))
    }
}
pub trait DaoCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        bolao_program: ActorId,
    ) -> sails_rs::client::PendingCtor<DaoProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> DaoCtors for sails_rs::client::Deployment<DaoProgram, E> {
    type Env = E;
    fn new(
        self,
        bolao_program: ActorId,
    ) -> sails_rs::client::PendingCtor<DaoProgram, io::New, Self::Env> {
        self.pending_ctor((bolao_program,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (bolao_program: ActorId) -> ());
}

pub mod service {
    use super::*;
    pub trait Service {
        type Env: sails_rs::client::GearEnv;
        fn set_bolao_program(
            &mut self,
            new_bolao: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetBolaoProgram, Self::Env>;
        fn set_owner(
            &mut self,
            new_owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetOwner, Self::Env>;
        fn register_bolao_code(
            &mut self,
            code_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::RegisterBolaoCode, Self::Env>;
        fn deploy_bolao(
            &mut self,
            admin: ActorId,
            salt: Vec<u8>,
            gas_limit: u64,
        ) -> sails_rs::client::PendingCall<io::DeployBolao, Self::Env>;
        fn create_proposal(
            &mut self,
            kind: super::ProposalKind,
            description: String,
        ) -> sails_rs::client::PendingCall<io::CreateProposal, Self::Env>;
        fn vote(
            &mut self,
            proposal_id: u64,
            choice: super::VoteChoice,
        ) -> sails_rs::client::PendingCall<io::Vote, Self::Env>;
        fn finalize_proposal(
            &mut self,
            proposal_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeProposal, Self::Env>;
        fn execute(
            &mut self,
            proposal_id: u64,
        ) -> sails_rs::client::PendingCall<io::Execute, Self::Env>;
        fn query_state(&self) -> sails_rs::client::PendingCall<io::QueryState, Self::Env>;
        fn query_proposal(
            &self,
            proposal_id: u64,
        ) -> sails_rs::client::PendingCall<io::QueryProposal, Self::Env>;
        fn query_proposals(
            &self,
        ) -> sails_rs::client::PendingCall<io::QueryProposals, Self::Env>;
        fn query_vote(
            &self,
            proposal_id: u64,
            voter: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryVote, Self::Env>;
        fn query_bolao_instances(
            &self,
        ) -> sails_rs::client::PendingCall<io::QueryBolaoInstances, Self::Env>;
    }
    pub struct ServiceImpl;
    impl<E: sails_rs::client::GearEnv> Service for sails_rs::client::Service<ServiceImpl, E> {
        type Env = E;
        fn set_bolao_program(
            &mut self,
            new_bolao: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetBolaoProgram, Self::Env> {
            self.pending_call((new_bolao,))
        }
        fn set_owner(
            &mut self,
            new_owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetOwner, Self::Env> {
            self.pending_call((new_owner,))
        }
        fn register_bolao_code(
            &mut self,
            code_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::RegisterBolaoCode, Self::Env> {
            self.pending_call((code_id,))
        }
        fn deploy_bolao(
            &mut self,
            admin: ActorId,
            salt: Vec<u8>,
            gas_limit: u64,
        ) -> sails_rs::client::PendingCall<io::DeployBolao, Self::Env> {
            self.pending_call((admin, salt, gas_limit))
        }
        fn create_proposal(
            &mut self,
            kind: super::ProposalKind,
            description: String,
        ) -> sails_rs::client::PendingCall<io::CreateProposal, Self::Env> {
            self.pending_call((kind, description))
        }
        fn vote(
            &mut self,
            proposal_id: u64,
            choice: super::VoteChoice,
        ) -> sails_rs::client::PendingCall<io::Vote, Self::Env> {
            self.pending_call((proposal_id, choice))
        }
        fn finalize_proposal(
            &mut self,
            proposal_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeProposal, Self::Env> {
            self.pending_call((proposal_id,))
        }
        fn execute(
            &mut self,
            proposal_id: u64,
        ) -> sails_rs::client::PendingCall<io::Execute, Self::Env> {
            self.pending_call((proposal_id,))
        }
        fn query_state(&self) -> sails_rs::client::PendingCall<io::QueryState, Self::Env> {
            self.pending_call(())
        }
        fn query_proposal(
            &self,
            proposal_id: u64,
        ) -> sails_rs::client::PendingCall<io::QueryProposal, Self::Env> {
            self.pending_call((proposal_id,))
        }
        fn query_proposals(
            &self,
        ) -> sails_rs::client::PendingCall<io::QueryProposals, Self::Env> {
            self.pending_call(())
        }
        fn query_vote(
            &self,
            proposal_id: u64,
            voter: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryVote, Self::Env> {
            self.pending_call((proposal_id, voter))
        }
        fn query_bolao_instances(
            &self,
        ) -> sails_rs::client::PendingCall<io::QueryBolaoInstances, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(SetBolaoProgram (new_bolao: ActorId) -> ());
        sails_rs::io_struct_impl!(SetOwner (new_owner: ActorId) -> ());
        sails_rs::io_struct_impl!(RegisterBolaoCode (code_id: [u8; 32]) -> ());
        sails_rs::io_struct_impl!(DeployBolao (admin: ActorId, salt: Vec<u8>, gas_limit: u64) -> ());
        sails_rs::io_struct_impl!(CreateProposal (kind: super::super::ProposalKind, description: String) -> ());
        sails_rs::io_struct_impl!(Vote (proposal_id: u64, choice: super::super::VoteChoice) -> ());
        sails_rs::io_struct_impl!(FinalizeProposal (proposal_id: u64) -> ());
        sails_rs::io_struct_impl!(Execute (proposal_id: u64) -> ());
        sails_rs::io_struct_impl!(QueryState () -> super::super::IoDaoState);
        sails_rs::io_struct_impl!(QueryProposal (proposal_id: u64) -> Option<super::super::Proposal>);
        sails_rs::io_struct_impl!(QueryProposals () -> Vec<super::super::Proposal>);
        sails_rs::io_struct_impl!(QueryVote (proposal_id: u64, voter: ActorId) -> Option<super::super::VoteChoice>);
        sails_rs::io_struct_impl!(QueryBolaoInstances () -> Vec<super::super::BolaoInstance>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum ServiceEvents {
            ProposalCreated((u64, ActorId)),
            Voted((u64, ActorId, super::super::VoteChoice)),
            ProposalFinalized((u64, super::super::ProposalStatus)),
            ProposalExecuted(u64),
            BolaoCallDispatched(u64),
            BolaoDeployed((ActorId, ActorId)),
            BolaoCodeRegistered,
            GovernanceParamUpdated,
            OwnerChanged(ActorId),
        }
        impl sails_rs::client::Event for ServiceEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "ProposalCreated",
                "Voted",
                "ProposalFinalized",
                "ProposalExecuted",
                "BolaoCallDispatched",
                "BolaoDeployed",
                "BolaoCodeRegistered",
                "GovernanceParamUpdated",
                "OwnerChanged",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for ServiceImpl {
            type Event = ServiceEvents;
        }
    }
}

// ── Type definitions (mirrors app/src/services/types.rs) ─────────────────────

#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum VoteChoice {
    Yes,
    No,
    Abstain,
}

#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ProposalStatus {
    Active,
    Defeated,
    Succeeded,
    Executed,
    Expired,
}

#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ProposalKind {
    AddPhase {
        name: String,
        start_time: u64,
        end_time: u64,
        points_weight: u32,
    },
    AddMatch {
        phase: String,
        home: String,
        away: String,
        kick_off: u64,
    },
    SetOracleAuthorized {
        oracle: ActorId,
        authorized: bool,
    },
    FinalizePodium {
        champion: String,
        runner_up: String,
        third_place: String,
    },
    CancelMatchResult {
        match_id: u64,
    },
    DeployBolao {
        admin: ActorId,
        salt: Vec<u8>,
        gas_limit: u64,
    },
    SetQuorum {
        new_quorum_bps: u16,
    },
    SetVotingPeriod {
        new_voting_period: u64,
    },
    SetDefaultBolao {
        new_bolao: ActorId,
    },
}

#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Proposal {
    pub id: u64,
    pub proposer: ActorId,
    pub kind: ProposalKind,
    pub description: String,
    pub start_time: u64,
    pub end_time: u64,
    pub yes: u32,
    pub no: u32,
    pub abstain: u32,
    pub status: ProposalStatus,
    pub executed: bool,
}

#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct BolaoInstance {
    pub program_id: ActorId,
    pub admin: ActorId,
    pub deployed_at: u64,
}

#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IoDaoState {
    pub owner: ActorId,
    pub bolao_program: ActorId,
    pub kyc_contract: Option<ActorId>,
    pub quorum_bps: u16,
    pub voting_period: u64,
    pub proposal_count: u64,
    pub bolao_code_registered: bool,
    pub bolao_instance_count: u32,
}
