// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct DaoProgram;
impl sails_rs::client::Program for DaoProgram {}
pub trait Dao {
    type Env: sails_rs::client::GearEnv;
    fn service(&self) -> sails_rs::client::Service<service::ServiceImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> Dao for sails_rs::client::Actor<DaoProgram, E> {
    type Env = E;
    fn service(&self) -> sails_rs::client::Service<service::ServiceImpl, Self::Env> {
        self.service(stringify!(Service))
    }
}
pub trait DaoCtors {
    type Env: sails_rs::client::GearEnv;
    /// Initialise the DAO.
    ///
    /// `bolao_program` — The BolaoCore program that governance proposals will
    /// dispatch to by default. Can be updated later via set_bolao_program() or
    /// a SetDefaultBolao governance proposal.
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        bolao_program: ActorId,
    ) -> sails_rs::client::PendingCtor<DaoProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> DaoCtors for sails_rs::client::Deployment<DaoProgram, E> {
    type Env = E;
    fn new(
        self,
        bolao_program: ActorId,
    ) -> sails_rs::client::PendingCtor<DaoProgram, io::New, Self::Env> {
        self.pending_ctor((bolao_program,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (bolao_program: ActorId) -> ());
}

pub mod service {
    use super::*;
    pub trait Service {
        type Env: sails_rs::client::GearEnv;
        fn add_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddAdmin, Self::Env>;
        /// Create a new governance proposal. Open to any caller.
        fn create_proposal(
            &mut self,
            kind: ProposalKind,
            description: String,
        ) -> sails_rs::client::PendingCall<io::CreateProposal, Self::Env>;
        /// Deploy a new BolaoCore program immediately (no governance vote required).
        /// Owner-only. The factory records the new instance in bolao_instances.
        ///
        /// `admin`     — Initial admin of the new BolaoCore instance.
        /// Pass `exec::program_id()` to make this DAO the admin.
        /// `salt`      — Unique bytes used to derive the deterministic program address.
        /// `gas_limit` — Gas forwarded to the BolaoCore init handler.
        /// Use DEFAULT_BOLAO_DEPLOY_GAS as a starting point.
        fn deploy_bolao(
            &mut self,
            admin: ActorId,
            salt: Vec<u8>,
            gas_limit: u64,
        ) -> sails_rs::client::PendingCall<io::DeployBolao, Self::Env>;
        /// Execute a proposal that has reached Succeeded status.
        /// Permissionless — any caller may trigger execution.
        ///
        /// If the proposal is still Active, execution panics.
        /// If the proposal Defeated/Expired, its status is updated and the call returns.
        fn execute(
            &mut self,
            proposal_id: u64,
        ) -> sails_rs::client::PendingCall<io::Execute, Self::Env>;
        /// Compute and persist the final status of a proposal after voting ends.
        /// Permissionless — anyone can call this once `end_time` has passed.
        fn finalize_proposal(
            &mut self,
            proposal_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeProposal, Self::Env>;
        fn force_withdraw_vara(
            &mut self,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ForceWithdrawVara, Self::Env>;
        /// Register the WASM code_id (32-byte Blake2 hash) of the BolaoCore binary.
        /// Must be called before deploy_bolao() or executing a DeployBolao proposal.
        /// Owner-only.
        fn register_bolao_code(
            &mut self,
            code_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::RegisterBolaoCode, Self::Env>;
        fn remove_admin(
            &mut self,
            admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveAdmin, Self::Env>;
        /// Update the default BolaoCore program that governance proposals dispatch to.
        /// Owner-only.
        fn set_bolao_program(
            &mut self,
            new_bolao: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetBolaoProgram, Self::Env>;
        /// Transfer ownership of this DAO to a new address.
        /// Owner-only. Single-step — use with care.
        fn set_owner(
            &mut self,
            new_owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetOwner, Self::Env>;
        /// Cast a vote on an active proposal. Each address may vote once per proposal.
        fn vote(
            &mut self,
            proposal_id: u64,
            choice: VoteChoice,
        ) -> sails_rs::client::PendingCall<io::Vote, Self::Env>;
        fn withdraw_vara(
            &mut self,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawVara, Self::Env>;
        /// Returns all BolaoCore instances deployed by this DAO's factory.
        fn query_bolao_instances(
            &self,
        ) -> sails_rs::client::PendingCall<io::QueryBolaoInstances, Self::Env>;
        fn query_proposal(
            &self,
            proposal_id: u64,
        ) -> sails_rs::client::PendingCall<io::QueryProposal, Self::Env>;
        fn query_proposals(&self) -> sails_rs::client::PendingCall<io::QueryProposals, Self::Env>;
        fn query_state(&self) -> sails_rs::client::PendingCall<io::QueryState, Self::Env>;
        fn query_vote(
            &self,
            proposal_id: u64,
            voter: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryVote, Self::Env>;
    }
    pub struct ServiceImpl;
    impl<E: sails_rs::client::GearEnv> Service for sails_rs::client::Service<ServiceImpl, E> {
        type Env = E;
        fn add_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddAdmin, Self::Env> {
            self.pending_call((new_admin,))
        }
        fn create_proposal(
            &mut self,
            kind: ProposalKind,
            description: String,
        ) -> sails_rs::client::PendingCall<io::CreateProposal, Self::Env> {
            self.pending_call((kind, description))
        }
        fn deploy_bolao(
            &mut self,
            admin: ActorId,
            salt: Vec<u8>,
            gas_limit: u64,
        ) -> sails_rs::client::PendingCall<io::DeployBolao, Self::Env> {
            self.pending_call((admin, salt, gas_limit))
        }
        fn execute(
            &mut self,
            proposal_id: u64,
        ) -> sails_rs::client::PendingCall<io::Execute, Self::Env> {
            self.pending_call((proposal_id,))
        }
        fn finalize_proposal(
            &mut self,
            proposal_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeProposal, Self::Env> {
            self.pending_call((proposal_id,))
        }
        fn force_withdraw_vara(
            &mut self,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ForceWithdrawVara, Self::Env> {
            self.pending_call((to, amount))
        }
        fn register_bolao_code(
            &mut self,
            code_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::RegisterBolaoCode, Self::Env> {
            self.pending_call((code_id,))
        }
        fn remove_admin(
            &mut self,
            admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveAdmin, Self::Env> {
            self.pending_call((admin,))
        }
        fn set_bolao_program(
            &mut self,
            new_bolao: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetBolaoProgram, Self::Env> {
            self.pending_call((new_bolao,))
        }
        fn set_owner(
            &mut self,
            new_owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetOwner, Self::Env> {
            self.pending_call((new_owner,))
        }
        fn vote(
            &mut self,
            proposal_id: u64,
            choice: VoteChoice,
        ) -> sails_rs::client::PendingCall<io::Vote, Self::Env> {
            self.pending_call((proposal_id, choice))
        }
        fn withdraw_vara(
            &mut self,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawVara, Self::Env> {
            self.pending_call((to, amount))
        }
        fn query_bolao_instances(
            &self,
        ) -> sails_rs::client::PendingCall<io::QueryBolaoInstances, Self::Env> {
            self.pending_call(())
        }
        fn query_proposal(
            &self,
            proposal_id: u64,
        ) -> sails_rs::client::PendingCall<io::QueryProposal, Self::Env> {
            self.pending_call((proposal_id,))
        }
        fn query_proposals(&self) -> sails_rs::client::PendingCall<io::QueryProposals, Self::Env> {
            self.pending_call(())
        }
        fn query_state(&self) -> sails_rs::client::PendingCall<io::QueryState, Self::Env> {
            self.pending_call(())
        }
        fn query_vote(
            &self,
            proposal_id: u64,
            voter: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryVote, Self::Env> {
            self.pending_call((proposal_id, voter))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddAdmin (new_admin: ActorId) -> ());
        sails_rs::io_struct_impl!(CreateProposal (kind: super::ProposalKind, description: String) -> ());
        sails_rs::io_struct_impl!(DeployBolao (admin: ActorId, salt: Vec<u8>, gas_limit: u64) -> ());
        sails_rs::io_struct_impl!(Execute (proposal_id: u64) -> ());
        sails_rs::io_struct_impl!(FinalizeProposal (proposal_id: u64) -> ());
        sails_rs::io_struct_impl!(ForceWithdrawVara (to: ActorId, amount: u128) -> ());
        sails_rs::io_struct_impl!(RegisterBolaoCode (code_id: [u8; 32]) -> ());
        sails_rs::io_struct_impl!(RemoveAdmin (admin: ActorId) -> ());
        sails_rs::io_struct_impl!(SetBolaoProgram (new_bolao: ActorId) -> ());
        sails_rs::io_struct_impl!(SetOwner (new_owner: ActorId) -> ());
        sails_rs::io_struct_impl!(Vote (proposal_id: u64, choice: super::VoteChoice) -> ());
        sails_rs::io_struct_impl!(WithdrawVara (to: ActorId, amount: u128) -> ());
        sails_rs::io_struct_impl!(QueryBolaoInstances () -> Vec<super::BolaoInstance>);
        sails_rs::io_struct_impl!(QueryProposal (proposal_id: u64) -> Option<super::Proposal>);
        sails_rs::io_struct_impl!(QueryProposals () -> Vec<super::Proposal>);
        sails_rs::io_struct_impl!(QueryState () -> super::IoDaoState);
        sails_rs::io_struct_impl!(QueryVote (proposal_id: u64, voter: ActorId) -> Option<super::VoteChoice>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum ServiceEvents {
            /// A new governance proposal was created. (proposal_id, proposer)
            ProposalCreated((u64, ActorId)),
            /// A vote was cast. (proposal_id, voter, choice)
            Voted((u64, ActorId, VoteChoice)),
            /// Voting ended and the final status was computed. (proposal_id, status)
            ProposalFinalized((u64, ProposalStatus)),
            /// A succeeded proposal was executed. (proposal_id)
            ProposalExecuted(u64),
            /// A governance command was dispatched to a BolaoCore program. (proposal_id)
            BolaoCallDispatched(u64),
            /// A new BolaoCore instance was deployed via the factory. (program_id, admin)
            BolaoDeployed((ActorId, ActorId)),
            BolaoCodeRegistered,
            GovernanceParamUpdated,
            /// The DAO owner was changed. (new_owner)
            OwnerChanged(ActorId),
            /// An additional admin was added. (admin)
            AdminAdded(ActorId),
            /// An admin was removed. (admin)
            AdminRemoved(ActorId),
            /// Admin withdrew VARA held by this DAO. (to, amount)
            VaraWithdrawn((ActorId, u128)),
            /// Owner emergency withdrawal of any VARA held by this DAO. (to, amount)
            ForceVaraWithdrawn((ActorId, u128)),
        }
        impl sails_rs::client::Event for ServiceEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "ProposalCreated",
                "Voted",
                "ProposalFinalized",
                "ProposalExecuted",
                "BolaoCallDispatched",
                "BolaoDeployed",
                "BolaoCodeRegistered",
                "GovernanceParamUpdated",
                "OwnerChanged",
                "AdminAdded",
                "AdminRemoved",
                "VaraWithdrawn",
                "ForceVaraWithdrawn",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for ServiceImpl {
            type Event = ServiceEvents;
        }
    }
}
/// All actions that can be proposed and voted on.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ProposalKind {
    /// Register a new tournament phase in BolaoCore.
    AddPhase {
        name: String,
        start_time: u64,
        end_time: u64,
        /// Scoring weight: 1 = group stage, >1 = knockout rounds.
        points_weight: u32,
    },
    /// Register a new match in BolaoCore.
    AddMatch {
        phase: String,
        home: String,
        away: String,
        kick_off: u64,
    },
    /// Grant or revoke oracle authority on BolaoCore.
    SetOracleAuthorized { oracle: ActorId, authorized: bool },
    /// Finalise the tournament podium on BolaoCore.
    FinalizePodium {
        champion: String,
        runner_up: String,
        third_place: String,
    },
    /// Cancel an oracle-proposed result that is still inside the challenge window.
    /// Maps to BolaoCore::cancel_proposed_result(match_id).
    CancelMatchResult { match_id: u64 },
    /// Deploy a new BolaoCore program via the on-chain factory.
    /// `salt` must be unique per deployment to avoid deterministic address collisions.
    DeployBolao {
        admin: ActorId,
        salt: Vec<u8>,
        gas_limit: u64,
    },
    /// Change the minimum quorum (basis points, 10 000 = 100 %).
    SetQuorum { new_quorum_bps: u16 },
    /// Change the voting window duration (milliseconds).
    SetVotingPeriod { new_voting_period: u64 },
    /// Update the default BolaoCore program that governance dispatches to.
    SetDefaultBolao { new_bolao: ActorId },
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum VoteChoice {
    Yes,
    No,
    Abstain,
}
/// Metadata for a BolaoCore instance deployed via the DAO factory.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct BolaoInstance {
    pub program_id: ActorId,
    pub admin: ActorId,
    /// Block timestamp (ms) at which the program was created.
    pub deployed_at: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Proposal {
    pub id: u64,
    pub proposer: ActorId,
    pub kind: ProposalKind,
    pub description: String,
    pub start_time: u64,
    pub end_time: u64,
    pub yes: u32,
    pub no: u32,
    pub abstain: u32,
    pub status: ProposalStatus,
    pub executed: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ProposalStatus {
    Active,
    Defeated,
    Succeeded,
    Executed,
    /// Reserved for future time-lock extensions.
    Expired,
}
/// Read-only projection of DaoState returned by query_state().
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IoDaoState {
    pub owner: ActorId,
    pub admins: Vec<ActorId>,
    /// Default BolaoCore program that governance proposals dispatch to.
    pub bolao_program: ActorId,
    pub kyc_contract: Option<ActorId>,
    pub quorum_bps: u16,
    pub voting_period: u64,
    pub proposal_count: u64,
    /// True if a BolaoCore WASM code_id has been registered via register_bolao_code().
    pub bolao_code_registered: bool,
    /// Number of BolaoCore instances deployed via this DAO's factory.
    pub bolao_instance_count: u32,
}
